-- Database: Olist_ecommerce

-- DROP DATABASE IF EXISTS "Olist_ecommerce";

CREATE DATABASE "Olist_ecommerce"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_India.1252'
    LC_CTYPE = 'English_India.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

DROP TABLE CUSTOMERS,ORDER_ITEMS,ORDER_PAYEMENTS

SELECT * FROM CUSTOMERS

ALTER TABLE CUSTOMERS ADD PRIMARY KEY (CUSTOMERID);
ALTER TABLE ORDERS ADD PRIMARY KEY (ORDERID);
ALTER TABLE SELLERS ADD PRIMARY KEY (SELLER_ID);
ALTER TABLE PRODUCTS ADD PRIMARY KEY (PRODUCT_ID);
ALTER TABLE ORDER_REVIEWS ADD PRIMARY KEY (REVIEW_ID,ORDER_ID);

ALTER TABLE ORDERS ADD CONSTRAINT fk_order_customer FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)